### PR TITLE
Set default image tag from 1.0.4 to latest

### PR DESCRIPTION
**Pull request by isnuryusuf**
### Please check if the PR fulfills these requirements
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (Bugfix, feature, docs update, ...)
…

### What is the current behavior? (You can also link to an open issue here)
…

### What is the new behavior (if this is a feature change)?
…

### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
…

### Other information:
…

### CODE REVIEW

**Comment by angelbarrera92** [comment]
Ciao @isnuryusuf 

Thanks for your contribution. We have to think about it. Currently, these two files are automatically updated using bumpversion on each release. 

Config file: https://github.com/k8spin/k8spin-operator/blob/master/.bumpversion.cfg

As far as these files are used in the e2e pipeline, we have to be sure before merge it.

Why do you consider `latest` is a better solution?

**Comment by isnuryusuf** [comment]
Hi @angelbarrera92  thanks for review
the reason is, the image tag 1.0.4 is not available on docker hub, so will be failed when pulling the image
is there something missing from my side?

**Comment by angelbarrera92** [comment]
> Hi @angelbarrera92 thanks for review
> the reason is, the image tag 1.0.4 is not available on docker hub, so will be failed when pulling the image
> is there something missing from my side?

🤔 you're right! 
So this is a bug. 

We are using the `deployments/kubernetes` to run e2e tests. Our recommendation is to deploy k8spin using helm.
So as a workaround while we check and fix this issue is to deploy it using helm (or feel free to render it using helm template command).

Thanks for spotting it!

**Pull request closed without merging**
